In [1]:
import numpy as np

Q1- Write a NumPy program to test whether none of the elements of a given array is zero

In [2]:
def question1(arr):
    check=np.all(np.array(arr))
    if check:
        return 'no zero'
    else:
        return 'contain zero'

In [3]:
check1=question1([1,0,3,4])

check1

'contain zero'

Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero

In [4]:
def question2(arr):
    check=np.any(np.array(arr))
    if check:
        return 'contain non-zero'
    else:
        return 'no non-zero'

In [5]:
check2=question2([0,2,0])

check2

'contain non-zero'

Q3- Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given 

In [6]:
def question3(arr1,arr2):
    arr1=np.array(arr1)
    arr2=np.array(arr2)
    assert arr1.shape==arr2.shape ,'cant compare'
    equal=np.equal(arr1,arr2)
    equal_tolerance=np.allclose(arr1,arr2)
    return equal,equal_tolerance

equal,equal_tolerance=question3([0,2,3,5.9999999999999999],[0,2,3,6])

In [7]:
equal

array([ True,  True,  True,  True])

In [8]:
equal_tolerance

True

Q4- Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [9]:
def question4():
    zeros=np.zeros(10)
    ones=np.ones(10)
    fives=ones*5
    return zeros,ones,fives

zeros,ones,fives=question4()

In [10]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Q5- Write a NumPy program to create an array of the integers from 30 to70

In [13]:
def question5():
    return np.array(range(30,71))

arr_q5=question5()

In [14]:
arr_q5

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

Q6- Write a NumPy program to create a 3x3 identity matrix 

In [15]:
def question6():
    return np.identity(3)
    
i=question6()

In [16]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q7- Write a NumPy program to generate a random number between 0 and 1

In [17]:
def question7():
    return np.random.normal(0,1,1)

rand_num=question7()

In [18]:
rand_num

array([-0.52479648])

Q8- Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [19]:
rand_nums = np.random.normal(0,1,15)

In [20]:
rand_nums

array([-0.89432633,  1.49055467,  1.21445628, -1.51020469,  1.05862616,
       -0.28746601,  0.85396997, -0.04132286,  0.98192782,  2.41422746,
        0.75239368, -0.39165595, -2.09425775,  1.42444054, -0.91424897])

Q9- Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.

In [21]:
arr_q9=np.array(range(15,56))
arr_q9[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

Q10- Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 

In [22]:
arr_q10=np.random.randint(0,11,5)
arr_q10 

array([7, 7, 5, 6, 9])

Q11- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [23]:
arr_q11=np.zeros((10,10))
arr_q11[0,:]=1
arr_q11[:,0]=1
arr_q11[-1,:]=1
arr_q11[:,-1]=1

arr_q11

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Q12- Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [24]:
arr_q12=np.diag([1,2,3,4,5])

In [25]:
arr_q12

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Q13- Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.

In [26]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5,6,7,8,9])
np.savez('test.npz', first=arr1,second=arr2)

In [27]:
with np.load('test.npz') as data:
    first_arr = data['first']
    second_arr = data['second']

In [28]:
first_arr

array([1, 2, 3, 4, 5])

In [29]:
second_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Q14- Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [32]:
arr_q14=np.zeros((4,4))
arr_q14[::2, 1::2]=1
arr_q14[1::2, ::2]=1


arr_q14

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Q15- Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [31]:
arr_q15=np.random.rand(40)
arr_q15

array([0.16459068, 0.14753667, 0.91147115, 0.18741787, 0.21089754,
       0.94961073, 0.20946343, 0.89056888, 0.32254279, 0.64750268,
       0.22732041, 0.12209514, 0.29486569, 0.38638372, 0.65668495,
       0.700003  , 0.95322321, 0.91663289, 0.65027922, 0.37001251,
       0.80143867, 0.41651727, 0.93892307, 0.87483297, 0.88098613,
       0.06755342, 0.79437609, 0.43816714, 0.39279917, 0.80027881,
       0.06586703, 0.93100494, 0.29305621, 0.74785625, 0.75967178,
       0.21423982, 0.6570076 , 0.43733458, 0.14924614, 0.49093315])

Q16- Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [30]:
def question16(arr,num):
    arr=np.array(arr)
    
    less=arr[arr < num]
    greater=arr[arr > num]
    
    return less,greater
   

question16([[1, 3, 7],[5, 6, 9],[4, 30, 20]],5)


(array([1, 3, 4]), array([ 7,  6,  9, 30, 20]))